# -*- coding: utf-8 -*-
"""final08

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y8rtnKAIddSut92PV_OcFzQiymwJigxZ
"""

def check_even_odd():
    while True:
        print("=" * 40)
        print("      🔢 โปรแกรมตรวจสอบเลขคู่ / เลขคี่")
        print("=" * 40)

        user_input = input("กรุณาใส่ตัวเลข (หรือพิมพ์ q เพื่อออก): ")

        if user_input.lower() == 'q':
            print("\n👋 ขอบคุณที่ใช้งานโปรแกรม")
            break

        try:
            number = int(user_input)

            print("-" * 40)
            if number % 2 == 0:
                print(f"✨ ผลลัพธ์: {number} เป็น 'เลขคู่'")
            else:
                print(f"✨ ผลลัพธ์: {number} เป็น 'เลขคี่'")
            print("-" * 40)

        except ValueError:
            print("⚠ กรุณากรอกตัวเลขจำนวนเต็มเท่านั้น!")

        print()  # เว้นบรรทัดก่อนเริ่มรอบใหม่


# เรียกใช้งานโปรแกรม
check_even_odd()#V.2