# -*- coding: utf-8 -*-
"""final08

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ebT8Xi2PH0SyAG-HHDUee9XD2BRi6NC
"""
V.1
print("โปรแกรมตรวจสอบเลขคู่ เลขคี่")
print()  # เว้นบรรทัด

number = int(input("ใส่ตัวเลขค้าบ: "))

if number % 2 == 0:
    print("เลข", number, "เป็นเลขคู่")
else:
    print("เลข", number, "เป็นเลขคี่")
