# -*- coding: utf-8 -*-
"""final08

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ebT8Xi2PH0SyAG-HHDUee9XD2BRi6NC
"""

#V.1
print("โปรแกรมตรวจสอบเลขคู่ เลขคี่")
print()  # เว้นบรรทัด

number = int(input("ใส่ตัวเลขค้าบ: "))

if number % 2 == 0:
    print("เลข", number, "เป็นเลขคู่")
else:
    print("เลข", number, "เป็นเลขคี่")

#V.2
def check_even_odd():
    while True:
        print("=" * 40)
        print("      🔢 โปรแกรมตรวจสอบเลขคู่ / เลขคี่")
        print("=" * 40)

        user_input = input("กรุณาใส่ตัวเลข (หรือพิมพ์ q เพื่อออก): ")

        if user_input.lower() == 'q':
            print("\n👋 ขอบคุณที่ใช้งานโปรแกรม")
            break

        try:
            number = int(user_input)

            print("-" * 40)
            if number % 2 == 0:
                print(f"✨ ผลลัพธ์: {number} เป็น 'เลขคู่'")
            else:
                print(f"✨ ผลลัพธ์: {number} เป็น 'เลขคี่'")
            print("-" * 40)

        except ValueError:
            print("⚠ กรุณากรอกตัวเลขจำนวนเต็มเท่านั้น!")

        print()  # เว้นบรรทัดก่อนเริ่มรอบใหม่


# เรียกใช้งานโปรแกรม
check_even_odd()